### ISSUE TITLE
KML Parser example doesn't appear to work

### ISSUE THREAD

**Issue by arktisma** [simplegeo/polymaps#32] opened 2010-09-25 03:58 UTC
As per the title... Or is it doing something imperceptible... ?

Tested in latest Firefox, Chrome & Safari on mac.

**Comment by mbostock** [comment] 2010-09-25 05:37
I see. Yes, the KML transcoder wasn't setting the type "FeatureCollection" on the GeoJSON. I've fixed that in my local branch and it will be in the next release. In the meantime, please feel free to patch this into your code:

http://github.com/mbostock/polymaps/commit/7033e1cace8956fbd96fc706b719468cd8a95fbc

**Comment by arktisma** [comment] 2010-09-25 05:45
Cool, thanks, it's working now.

I have another small problem - If I have lines that cross the equator, they scale oddly. I'm not sure what the technical name for it is, so here is a screengrab: http://tinyurl.com/22vubba

**Comment by mbostock** [comment] 2010-09-25 05:51
Hmm, yes, that's an interesting problem. The issue is not the equator, but that your points cross -180° longitude, wrapping around to +180°. I suppose the right thing to do here is to detect this wrap-around case when projecting LineStrings (and Polygons). You could try patching that in your data (subtracting 360° for the longitude for the coordinates currently displayed on the right), as a temporary fix.

**Comment by arktisma** [comment] 2010-09-25 06:04
Sorry, equator... I meant to say date line.... I'll have a look at patching my data...

Last question... In my KML data, I have <description> tags. Curiously, if I hover a mouse long enough over each placemark (the small dots in the image above), I actually get my <description> coming up as a sort of alt-tag. How can I capture that, and style it as a tooltip, or a popup? Here is what I mean: http://tinyurl.com/2wdbfea

**Closed as completed** 2010-09-25 12:37 UTC

**Comment by mbostock** [comment] 2010-09-25 16:46
Right, that part is implemented in kml.html in a load handler, using the `name` and `description` properties of your data:

```
f.element.appendChild(po.svg("title").appendChild(
    document.createTextNode(p.name + ": " + p.description))
    .parentNode);
```

If you want to style it as a more flexible (HTML) popup, take a look at the Tipsy example:

http://github.com/mbostock/polymaps/tree/master/examples/tipsy/

Tipsy is a plugin for jQuery that provides "Facebook-style" tooltips. The Tipsy example above activates the tooltip on click, similar to Google Maps, but you could also activate it on mouseover. Or do something like find the closest point to the mouse, and show the tooltip for that. If I have some time this weekend I'll try to put together a better example of this.

The other thing to look at is the new marker example which I'm developing, showing how to use custom SVG:

http://github.com/mbostock/polymaps/tree/master/examples/marker/

In your case, though, sounds like you're more interested in rich popups rather than custom marker display. But the vector markers with gradients are pretty so I thought I'd share. :)
