### ISSUE TITLE
Bounding Box Rendering Issue 

### ISSUE THREAD

**Issue by tyrauber** [simplegeo/polymaps#90] opened 2011-08-06 22:54 UTC
I am experiencing a rendering issue with bounding boxes for objects around the 180 degree meridian line.  The linked images demonstrate the problem:  http://imgur.com/a/npXeM

I am generating bounding boxes for multipolygon paths through the following calculation:

```
xmin = ymin = Float::MAX
xmax = ymax = -Float::MAX

  for geom in  geometry
    for g in geom
            if g[0] < xmin: xmin = g[0]; end
            if g[1] < ymin: ymin = g[1]; end
            if g[0] > xmax: xmax = g[0]; end
            if g[1] > ymax: ymax = g[1]; end
    end
      end
```

(Where geometry is an array of polygons, and geom is an array of lat/lng coordinates.) It works great for everything that does not cross over the meridian line at 180 degrees.  

The shape for Alaska, and counties within Alaska (that cross over the 180 degree line), all have this problem. 

If you take the Alaskan county Aleutians West, with a bounds of:

```
    [-175.91303, - 51.17509], [173.40338, - 57.30527]
```

or:

```
    [173.40338, - 57.30527], [-175.91303, - 51.17509]
```

Both exhibit the same problem.  The closest I have gotten is tweaking my import code to ignore all points over the meridian, but that seems like a poor solution.

I have been banging my head against this for days. Any ideas would be be greatly appreciated. Thanks a bunch.

**Comment by mbostock** [comment] 2011-08-07 04:30
This is a duplicate of #33. Unfortunately, I don't know what the right general solution is…

**Comment by tyrauber** [comment] 2011-08-08 19:23
Sorry, for issuing a duplicate bug. I guess I am relieved the bug isn't in my code, although I would still like to find a workaround.   Why is it that shapes with many boundary points don't exhibit this problem? Such as the shape of Alaska? More data points?

I thought that if I added an extra two points on the meridian at the top and bottom of the bounding box, that might force the polygon to render correctly, but that doesn't seem to matter.

**Comment by mbostock** [comment] 2011-08-08 19:37
I'm not sure. Does Alaska actually have a polygon that crosses the antimeridian? It looks like it's just the archipelago that extends out that far, but there's no little island that straddles the line.

**Comment by tyrauber** [comment] 2011-08-08 20:10
No. You are correct. It appears that Alaska, and all other objects that would exhibit this behavior are in fact multi-polygon shapes. A quick test indicates that no polygon that contains a positive latitude, also contains a negative latitude.   I guess that is a solution. Double bounding boxes for those objects that will exhibit this behavior. One on either side of the antimeridian.

**Closed as completed** 2011-08-21 18:02 UTC
